[package]
name = "rustls-pemfile"
version = "0.1.0"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
edition = "2018"
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
description = "Rustls is a modern TLS library written in Rust."
homepage = "https://github.com/rustls/pemfile"
repository = "https://github.com/rustls/pemfile"
categories = ["network-programming", "cryptography"]

[dependencies]
base64 = "0.13.0"
